{
 "title": "Variant",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Scrape interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "variant_scrape_interval" }
   ]
  },
  {
   "title": "Total incursions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "variant_incursions_total" }
   ]
  },
  {
   "title": "Detected variants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "variant_scrape_configs_detected"
    }
   ]
  }
 ]
}